/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.ITimer;

public class ExampleStatemachine implements IExampleStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private boolean start;
		
		public void raiseStart() {
			start = true;
		}
		
		private boolean white;
		
		public void raiseWhite() {
			white = true;
		}
		
		private boolean black;
		
		public void raiseBlack() {
			black = true;
		}
		
		private boolean blue;
		
		public void raiseBlue() {
			blue = true;
		}
		
		private long whiteTime;
		
		public long getWhiteTime() {
			return whiteTime;
		}
		
		public void setWhiteTime(long value) {
			this.whiteTime = value;
		}
		
		private long blackTime;
		
		public long getBlackTime() {
			return blackTime;
		}
		
		public void setBlackTime(long value) {
			this.blackTime = value;
		}
		
		private long blueTime;
		
		public long getBlueTime() {
			return blueTime;
		}
		
		public void setBlueTime(long value) {
			this.blueTime = value;
		}
		
		protected void clearEvents() {
			start = false;
			white = false;
			black = false;
			blue = false;
		}
	}
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		_region0_Init,
		_region0_Black,
		_region0_White,
		$NullState$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[2];
	public ExampleStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setWhiteTime(60);
		
		sCInterface.setBlackTime(60);
		
		sCInterface.setBlueTime(60);
	}
	
	public void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence__region0_default();
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case _region0_Init:
				_region0_Init_react(true);
				break;
			case _region0_Black:
				_region0_Black_react(true);
				break;
			case _region0_White:
				_region0_White_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public void exit() {
		exitSequence__region0();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case _region0_Init:
			return stateVector[0] == State._region0_Init;
		case _region0_Black:
			return stateVector[0] == State._region0_Black;
		case _region0_White:
			return stateVector[0] == State._region0_White;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public void timeElapsed(int eventID) {
		timeEvents[eventID] = true;
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public void raiseStart() {
		sCInterface.raiseStart();
	}
	
	public void raiseWhite() {
		sCInterface.raiseWhite();
	}
	
	public void raiseBlack() {
		sCInterface.raiseBlack();
	}
	
	public void raiseBlue() {
		sCInterface.raiseBlue();
	}
	
	public long getWhiteTime() {
		return sCInterface.getWhiteTime();
	}
	
	public void setWhiteTime(long value) {
		sCInterface.setWhiteTime(value);
	}
	
	public long getBlackTime() {
		return sCInterface.getBlackTime();
	}
	
	public void setBlackTime(long value) {
		sCInterface.setBlackTime(value);
	}
	
	public long getBlueTime() {
		return sCInterface.getBlueTime();
	}
	
	public void setBlueTime(long value) {
		sCInterface.setBlueTime(value);
	}
	
	/* Entry action for state 'Black'. */
	private void entryAction__region0_Black() {
		timer.setTimer(this, 0, (1 * 1000), false);
	}
	
	/* Entry action for state 'White'. */
	private void entryAction__region0_White() {
		timer.setTimer(this, 1, (1 * 1000), false);
	}
	
	/* Exit action for state 'Black'. */
	private void exitAction__region0_Black() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'White'. */
	private void exitAction__region0_White() {
		timer.unsetTimer(this, 1);
	}
	
	/* 'default' enter sequence for state Init */
	private void enterSequence__region0_Init_default() {
		nextStateIndex = 0;
		stateVector[0] = State._region0_Init;
	}
	
	/* 'default' enter sequence for state Black */
	private void enterSequence__region0_Black_default() {
		entryAction__region0_Black();
		nextStateIndex = 0;
		stateVector[0] = State._region0_Black;
	}
	
	/* 'default' enter sequence for state White */
	private void enterSequence__region0_White_default() {
		entryAction__region0_White();
		nextStateIndex = 0;
		stateVector[0] = State._region0_White;
	}
	
	/* 'default' enter sequence for region  */
	private void enterSequence__region0_default() {
		react__region0__entry_Default();
	}
	
	/* Default exit sequence for state Init */
	private void exitSequence__region0_Init() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Black */
	private void exitSequence__region0_Black() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction__region0_Black();
	}
	
	/* Default exit sequence for state White */
	private void exitSequence__region0_White() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction__region0_White();
	}
	
	/* Default exit sequence for region  */
	private void exitSequence__region0() {
		switch (stateVector[0]) {
		case _region0_Init:
			exitSequence__region0_Init();
			break;
		case _region0_Black:
			exitSequence__region0_Black();
			break;
		case _region0_White:
			exitSequence__region0_White();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react__region0__entry_Default() {
		enterSequence__region0_Init_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean _region0_Init_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.start) {
					exitSequence__region0_Init();
					enterSequence__region0_White_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean _region0_Black_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.black) {
					exitSequence__region0_Black();
					enterSequence__region0_White_default();
				} else {
					if (timeEvents[0]) {
						exitSequence__region0_Black();
						sCInterface.setBlackTime(sCInterface.getBlackTime() - 1);
						
						enterSequence__region0_Black_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean _region0_White_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (timeEvents[1]) {
					exitSequence__region0_White();
					sCInterface.setWhiteTime(sCInterface.getWhiteTime() - 1);
					
					enterSequence__region0_White_default();
				} else {
					if (sCInterface.white) {
						exitSequence__region0_White();
						enterSequence__region0_Black_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
}
